#pragma once

#include <angleshooter/PreCompiledHeaders.h>

#include "util/ResourceHolder.h"
#include "util/Keybinding.h"
#include "managers/FontHolder.h"
#include "managers/SoundHolder.h"
#include "managers/TextureHolder.h"
#include "managers/ShaderHolder.h"
#include "managers/InputManager.h"
#include "managers/OptionsManager.h"
#include "states/State.h"
#include "managers/StateManager.h"
#include "managers/AudioManager.h"

#include "menu/Widget.h"
#include "menu/Button.h"
#include "menu/Label.h"
#include "menu/Slider.h"
#include "menu/WidgetContainer.h"
#include "menu/IpButton.h"
#include "menu/NameButton.h"
#include "rendering/shaders/PostProcessing.h"
#include "rendering/shaders/BloomProcessing.h"
#include "rendering/WorldRenderer.h"
#include "util/ScoreEntry.h"
#include "states/MenuState.h"
#include "states/GameState.h"
#include "states/SettingsState.h"
#include "states/OnboardingState.h"
#include "states/PauseState.h"
#include "rendering/WorldRenderer.h"
#include "rendering/MapRenderer.h"
#include "game/ClientWorld.h"
#include "game/ClientPlayerEntity.h"

#include "AngleShooterClient.h"